from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.instagram.com/")
    page.get_by_role("button", name="Allow all cookies").click()
    page.get_by_label("Phone number, username, or email").click()
    page.get_by_label("Phone number, username, or email").fill("sadru1838")
    page.get_by_label("Password").click()
    page.get_by_label("Password").fill("far895tile620")
    page.get_by_role("button", name="Log in", exact=True).click()
    page.get_by_label("Phone number, username, or email").dblclick()
    page.get_by_label("Phone number, username, or email").fill("sadru1838team33f")
    page.get_by_label("Phone number, username, or email").press("Control+a")
    page.get_by_label("Phone number, username, or email").fill("team33f")
    page.get_by_role("button", name="Log in", exact=True).click()
    page.goto("https://www.instagram.com/accounts/onetap/?next=%2F")
    page.get_by_role("button", name="Save info").click()
    page.get_by_role("button", name="Turn On").click()
    page.get_by_role("link", name="team33f's profile picture Profile").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Edit profile", exact=True).click()
    page.get_by_role("main").locator("div").filter(has_text="CloseFacebook wordmark and family of apps logoNow in Accounts CenterTo make it e").first.click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("link", name="Facebook wordmark and family of apps logo Accounts Center Manage your connected experiences and account settings across Meta technologies. Personal details Password and security Ad preferences See more in Accounts Center").click()
    page.get_by_role("link", name="team33f\nInstagram").click()
    page.get_by_role("link", name="Name", exact=True).click()
    page.get_by_label("Name").fill("Samane Suranman")
    page.get_by_role("button", name="Done").click()
    page.get_by_role("link", name="Username").click()
    page.get_by_label("Username").click()
    page.get_by_label("Username").fill("team33f")
    page.get_by_role("button", name="Done").press("Control+Shift+C")
    page.goto("https://accountscenter.instagram.com/profiles/17841466524319495/username")

    # ---------------------
    context.close()
    browser.close()